name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn
      - name: Transpile Typescript and build react project
        run: yarn tsc ./public/electron.ts && yarn react-scripts build
      - name: Build/publish
        run: yarn electron-builder --publish=always
        env:
          GH_TOKEN: ${{ secrets.github_token }}
